/* 사원 */
DROP TABLE EMPLOYEE 
	CASCADE CONSTRAINTS;

/* 팀 */
DROP TABLE TEAM 
	CASCADE CONSTRAINTS;

/* 메세지 */
DROP TABLE MESSAGE 
	CASCADE CONSTRAINTS;

/* 게시물 */
DROP TABLE CONTENT 
	CASCADE CONSTRAINTS;

/* 게시판 */
DROP TABLE BOARD 
	CASCADE CONSTRAINTS;

/* 댓글 */
DROP TABLE REPLY 
	CASCADE CONSTRAINTS;

/* 직급 */
DROP TABLE POSITION 
	CASCADE CONSTRAINTS;

/* 사원 */
CREATE TABLE EMPLOYEE (
	EMPLOYEE_NO NVARCHAR2(10) NOT NULL, /* 사번 */
	TEAM_ID NVARCHAR2(10), /* 팀ID */
	EMAIL NVARCHAR2(50), /* 이메일 */
	EMPLOYEE_NAME NVARCHAR2(50), /* 이름 */
	JOIN_DATE DATE, /* 입사일 */
	PASSWORD NVARCHAR2(50), /* 암호 */
	IS_AUTHORITY NVARCHAR2(5), /* 인증여부 */
	LAST_LOGIN DATE, /* 최근로그인 */
	POSITION_ID NVARCHAR2(10), /* 직급_ID */
	ROLE NVARCHAR2(10), /* ROLE */
	IMAGE_URL NVARCHAR2(50) /* 이미지경로 */
);

CREATE UNIQUE INDEX PK_EMPLOYEE
	ON EMPLOYEE (
		EMPLOYEE_NO ASC
	);

ALTER TABLE EMPLOYEE
	ADD
		CONSTRAINT PK_EMPLOYEE
		PRIMARY KEY (
			EMPLOYEE_NO
		);

/* 팀 */
CREATE TABLE TEAM (
	TEAM_ID NVARCHAR2(10) NOT NULL, /* 팀ID */
	TEAM_NAME NVARCHAR2(50) /* 팀명 */
);

CREATE UNIQUE INDEX PK_TEAM
	ON TEAM (
		TEAM_ID ASC
	);

ALTER TABLE TEAM
	ADD
		CONSTRAINT PK_TEAM
		PRIMARY KEY (
			TEAM_ID
		);


/* 메세지 */
CREATE TABLE MESSAGE (
	RECEIVER_EMPLOYEE_NO NVARCHAR2(10), /* 수신인사번 */
	SENDER_EMPLOYEE_NO NVARCHAR2(10), /* 발신인사번 */
	MESSAGE_CONTENT NVARCHAR2(200), /* 내용 */
	WRITE_DATE DATE /* 발신일 */
);

/* 게시물 */
CREATE TABLE CONTENT (
	CONTENT_ID NVARCHAR2(100) NOT NULL, /* 게시물ID */
	EMPLOYEE_NO NVARCHAR2(10), /* 작성자사번 */
	CONTENT_TITLE NVARCHAR2(50), /* 제목 */
	CONTENT_CONTENT NVARCHAR2(2000), /* 내용 */
	TEAM_ID NVARCHAR2(10), /* 팀ID */
	BOARD_ID NVARCHAR2(10), /* 게시판ID */
	WRITE_DATE DATE /* 작성일 */
);

CREATE UNIQUE INDEX PK_CONTENT
	ON CONTENT (
		CONTENT_ID ASC
	);

ALTER TABLE CONTENT
	ADD
		CONSTRAINT PK_CONTENT
		PRIMARY KEY (
			CONTENT_ID
		);

/* 게시판 */
CREATE TABLE BOARD (
	BOARD_ID NVARCHAR2(10) NOT NULL, /* 게시판ID */
	BOARD_NAME NVARCHAR2(50), /* 게시판명 */
	BOARD_AUTHORITY NVARCHAR2(10), /* 접근권한 */
	IS_TEAM NVARCHAR2(5) /* 팀전용여부 */
);

CREATE UNIQUE INDEX PK_BOARD
	ON BOARD (
		BOARD_ID ASC
	);

ALTER TABLE BOARD
	ADD
		CONSTRAINT PK_BOARD
		PRIMARY KEY (
			BOARD_ID
		);

/* 댓글 */
CREATE TABLE REPLY (
	CONTENT_ID NVARCHAR2(100), /* 게시물ID */
	EMPLOYEE_NO NVARCHAR2(10), /* 작성자사번 */
	WRITE_DATE DATE, /* 작성시간 */
	REPLY_CONTENT NVARCHAR2(200) /* 댓글내용 */
);

/* 직급 */
CREATE TABLE POSITION (
	POSITION_ID NVARCHAR2(10) NOT NULL, /* 직급_ID */
	POSITION_NAME NVARCHAR2(50) /* 직급명 */
);

/* 스케줄 */
CREATE TABLE SCHEDULE (
	START_DATE NVARCHAR2(50), 
	END_DATE NVARCHAR2(50), 
	SCHEDULE_CONTENT NVARCHAR2(100), 
	EMPLOYEE_NO NVARCHAR2(10) /* 사번 */
);

CREATE UNIQUE INDEX PK_POSITION
	ON POSITION (
		POSITION_ID ASC
	);

ALTER TABLE POSITION
	ADD
		CONSTRAINT PK_POSITION
		PRIMARY KEY (
			POSITION_ID
		);