


INSERT INTO TEAM VALUES('DEV01','개발1팀');
INSERT INTO TEAM VALUES('DEV02','개발2팀');
INSERT INTO TEAM VALUES('DEV03','개발3팀');
INSERT INTO TEAM VALUES('DEV04','개발4팀');

INSERT INTO BOARD VALUES('NOTICE','공지사항',3,'N');
INSERT INTO BOARD VALUES('FREE','자유게시판',10,'N');
INSERT INTO BOARD VALUES('TEAM','팀게시판',10,'Y');


INSERT INTO POSITION VALUES('1','사장');
INSERT INTO POSITION VALUES('2','부사장');
INSERT INTO POSITION VALUES('3','전무');
INSERT INTO POSITION VALUES('4','상무');
INSERT INTO POSITION VALUES('5','이사');
INSERT INTO POSITION VALUES('6','부장');
INSERT INTO POSITION VALUES('7','차장');
INSERT INTO POSITION VALUES('8','과장');
INSERT INTO POSITION VALUES('9','대리');
INSERT INTO POSITION VALUES('10','사원');

INSERT INTO 
EMPLOYEE(
		EMPLOYEE_NO,
		TEAM_ID,
		EMAIL,
		EMPLOYEE_NAME,
		JOIN_DATE,
		POSITION_ID,
		PASSWORD,
		IS_AUTHORITY,
		ROLE,
		LAST_LOGIN) 
VALUES (
		'2016122910',
		'DEV03',	
		'tkdgjs1501@nate.com',
		'김상헌',
		SYSDATE,
		'10',
		'ADMIN',
		'Y',
		'ADMIN',
		SYSDATE
		)
		
		
INSERT INTO 
EMPLOYEE(
		EMPLOYEE_NO,
		TEAM_ID,
		EMAIL,
		EMPLOYEE_NAME,
		JOIN_DATE,
		POSITION_ID,
		PASSWORD,
		IS_AUTHORITY,
		ROLE,
		LAST_LOGIN) 
VALUES (
		'1',
		'DEV01',	
		'tkdgjs1501@nate.com',
		'사장',
		SYSDATE,
		'1',
		'1',
		'Y',
		'USER',
		SYSDATE
		)

				
